<?php

namespace AppBundle\Repository;

/**
 * PruebaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebaRepository extends \Doctrine\ORM\EntityRepository
{
}
