<?php

namespace AppBundle\Repository;

/**
 * Sys_ConexionBDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sys_ConexionBDRepository extends \Doctrine\ORM\EntityRepository
{
}
