<?php

namespace AppBundle\Repository;

/**
 * Sys_RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sys_RolRepository extends \Doctrine\ORM\EntityRepository
{
}
