<?php

namespace AppBundle\Repository;

/**
 * Sys_Conexion_BDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sys_Conexion_BDRepository extends \Doctrine\ORM\EntityRepository
{
}
