<?php

namespace AppBundle\Repository;

/**
 * Sys_ConsultaSQLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sys_ConsultaSQLRepository extends \Doctrine\ORM\EntityRepository
{
}
