<?php

namespace AppBundle\Repository;

/**
 * SysConexionBDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SysConexionBDRepository extends \Doctrine\ORM\EntityRepository
{
}
