# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    service_generico:
        class: AppBundle\Regla\GenericoRegla
        arguments: ["@doctrine.orm.entity_manager"]

    service_query:
        class: AppBundle\Regla\QuerysRegla
        arguments: ["@doctrine.orm.entity_manager"]

        
